"""
Central registry of Pakistan-based companies for the prospecting pipeline.
Filtered and ranked for candidate profile:
    Usairam Saeed - Full Stack Developer (React, Node.js, MongoDB)
    AI / ML / NLP, real-time systems, payments, scheduling, UI/UX.

Verticals covered:
    Finance/FinTech, Healthcare/HealthTech, Travel & Hospitality,
    E-Commerce & Retail, Media & Entertainment, Marketing & Advertising,
    Aviation & Logistics, Food & Agriculture, Education & Training,
    Construction & Manufacturing, GovTech, GreenTech, Cybersecurity,
    AI & Data Science.

Resume routing:
    AI & Data Science            -> Usairam_Saeed_EuroPass_CV.pdf
    All other verticals          -> Usairam Saeed.pdf
"""

CANDIDATE_EMAIL = "saeed.usairam@gmail.com"
DEFAULT_RESUME = "Usairam Saeed.pdf"
AI_RESUME = "Usairam_Saeed_EuroPass_CV.pdf"
AI_VERTICAL = "AI & Data Science"


def resume_for_vertical(vertical: str) -> str:
    """Return the resume file name to attach for a given vertical."""
    return AI_RESUME if vertical == AI_VERTICAL else DEFAULT_RESUME


# Each company: (name, website, notes, custom_requirement)
COMPANIES_BY_VERTICAL = {
    "Finance/FinTech": [
        ("SadaPay", "https://sadapay.pk",
         "Digital banking / wallet startup (now part of Papara).",
         "React + Node SaaS fintech; Stripe/payments exposure"),
        ("NayaPay", "https://nayapay.com",
         "Digital wallet and payments platform.",
         "Real-time wallet + MERN + UI/UX"),
        ("JazzCash", "https://www.jazzcash.com.pk",
         "Pakistan's largest mobile financial service.",
         "Large-scale fintech full-stack engineering"),
        ("Easypaisa", "https://easypaisa.com.pk",
         "Mobile payments and digital bank (Telenor Microfinance).",
         "Payments + real-time systems"),
        ("Finja", "https://finja.pk",
         "SME lending and payments platform.",
         "MERN + fintech; SaaS scale"),
        ("Abhi", "https://abhi.com.pk",
         "Earned-wage-access fintech for employees.",
         "Real-time transactions + SaaS dashboards"),
        ("Oraan", "https://www.oraan.com",
         "Women-focused fintech (digital committees / savings).",
         "Mobile-first fintech UX, React Native / React"),
        ("Tag", "https://tag.ag",
         "Digital banking and wallet startup.",
         "Full-stack fintech product engineering"),
        ("CreditBook", "https://creditbook.pk",
         "SME bookkeeping and credit app.",
         "Scalable SaaS + mobile + payments"),
        ("DBank", "https://dbank.com.pk",
         "Pakistan digital bank startup.",
         "Fintech UI/UX + payments + MERN"),
    ],

    "Healthcare/HealthTech": [
        ("Sehat Kahani", "https://sehatkahani.com",
         "Telemedicine platform connecting female doctors with patients.",
         "HealthTech SaaS + real-time video + scheduling"),
        ("Marham", "https://www.marham.pk",
         "Online doctor appointments and health consultations.",
         "Scheduling + payments + MERN"),
        ("Shifa4U", "https://www.shifa4u.com",
         "Virtual healthcare and lab booking.",
         "Telemedicine SaaS; React + Node"),
        ("oladoc", "https://oladoc.com",
         "Doctor booking and online consultation platform.",
         "Appointment scheduling + UI/UX + MERN"),
        ("Healthwire", "https://healthwire.pk",
         "Healthcare marketplace (doctors, labs, hospitals).",
         "Full-stack product engineering for healthcare"),
        ("DoctHERs", "https://docthers.com",
         "Female-doctor tele-health platform.",
         "Telehealth UX + SaaS platform"),
        ("MedIQ", "https://mediq.ai",
         "AI-enabled healthcare platform.",
         "AI-integrated HealthTech SaaS"),
        ("Dawaai", "https://dawaai.pk",
         "Online pharmacy and medicine delivery.",
         "E-commerce + payments + real-time inventory"),
    ],

    "Travel & Hospitality": [
        ("Sastaticket.pk", "https://www.sastaticket.pk",
         "Online travel booking platform.",
         "Payments + real-time booking systems"),
        ("Bookme.pk", "https://bookme.pk",
         "Ticketing for travel, events and cinema.",
         "Scheduling + payments SaaS"),
        ("Travelix", "https://travelix.pk",
         "Travel tech startup.",
         "Full-stack travel SaaS"),
        ("Roomph", "https://roomph.pk",
         "Hotel booking platform.",
         "Real-time inventory and bookings"),
        ("FindMyAdventure", "https://www.findmyadventure.pk",
         "Adventure and tour booking marketplace.",
         "UI/UX for booking funnels"),
        ("TravelPakistani", "https://travelpakistani.com",
         "Tour and travel marketplace.",
         "MERN + travel marketplace UX"),
        ("Pakistan Tours", "https://www.pakistantours.pk",
         "Domestic tours and hospitality.",
         "Booking engine + payments"),
    ],

    "E-Commerce & Retail": [
        ("Daraz Pakistan", "https://www.daraz.pk",
         "Largest e-commerce marketplace in Pakistan.",
         "React + Node scalable marketplace experience"),
        ("Bagallery", "https://www.bagallery.com",
         "Leading online beauty and fashion retailer.",
         "UI/UX improvements for checkout funnel"),
        ("Foodpanda Pakistan", "https://www.foodpanda.pk",
         "Food delivery platform; real-time ordering.",
         "Real-time systems and payments"),
        ("PriceOye", "https://priceoye.pk",
         "Electronics and mobile e-commerce platform.",
         "Full-stack product engineering"),
        ("Telemart", "https://www.telemart.pk",
         "Consumer electronics retailer.",
         "MERN stack full-stack development"),
        ("iShopping.pk", "https://ishopping.pk",
         "Online electronics and gadgets retailer.",
         "E-commerce + payments"),
        ("Symbios.pk", "https://www.symbios.pk",
         "E-commerce for electronics and home appliances.",
         "Catalog + search + payments"),
        ("Goto.com.pk", "https://goto.com.pk",
         "General e-commerce marketplace.",
         "React + Node marketplace engineering"),
        ("HumMart", "https://www.hummart.com",
         "Online grocery and essentials.",
         "Real-time inventory + delivery tracking"),
        ("Khaas.pk", "https://khaas.pk",
         "Online fashion and apparel store.",
         "UI/UX for fashion commerce"),
    ],

    "Media & Entertainment": [
        ("Tapmad TV", "https://www.tapmad.com",
         "OTT streaming platform for Pakistan.",
         "Streaming SaaS + payments + UX"),
        ("Patari", "https://patari.pk",
         "Music streaming service.",
         "Real-time streaming, React + Node"),
        ("Geo Group", "https://www.geo.tv",
         "Major Pakistani media group.",
         "Digital media platforms, full-stack"),
        ("ARY Digital Network", "https://arydigital.tv",
         "Television and digital media network.",
         "OTT / web platforms + MERN"),
        ("Dawn Media Group", "https://www.dawn.com",
         "Leading English-language media.",
         "News publishing platform, full-stack"),
        ("Express Media Group", "https://www.expressmedia.pk",
         "Newspaper, TV and digital media.",
         "Digital publishing + UI/UX"),
    ],

    "Marketing & Advertising": [
        ("Ogilvy Pakistan", "https://www.ogilvy.com.pk",
         "Global advertising agency with Pakistan office.",
         "UI/UX for campaign dashboards"),
        ("Adcom Leo Burnett", "https://leoburnett.com",
         "Leading advertising and marketing firm.",
         "Marketing tech platforms; full-stack"),
        ("Digitonics Labs", "https://digitonics.com",
         "Digital marketing agency (Karachi).",
         "React + Node SaaS dashboards"),
        ("Ignite Digital", "https://ignitedigital.com.pk",
         "Digital marketing and branding.",
         "Product engineering for marketing tools"),
        ("BrandVerse", "https://brandverse.com.pk",
         "Influencer marketing and ad platform.",
         "SaaS with 500-2000+ users"),
        ("Markhor Labs", "https://markhorlabs.com",
         "Digital product and marketing studio.",
         "MERN + modern UI/UX"),
        ("Grayscale", "https://grayscale.com.pk",
         "Creative and digital marketing agency.",
         "React front-end + dashboards"),
    ],

    "Aviation & Logistics": [
        ("TCS", "https://www.tcsexpress.com",
         "Largest courier and logistics company in Pakistan.",
         "Logistics SaaS + real-time tracking"),
        ("Leopards Courier", "https://www.leopardscourier.com",
         "Nationwide courier and delivery.",
         "Tracking systems + APIs"),
        ("Pakistan International Airlines", "https://www.piac.com.pk",
         "National flag carrier.",
         "Booking engine + payments"),
        ("AirSial", "https://airsial.com",
         "Domestic and international airline.",
         "Airline booking + real-time systems"),
        ("Swyft Logistics", "https://swyftlogistics.com",
         "Tech-enabled logistics startup.",
         "Real-time dispatch + dashboards"),
        ("PostEx", "https://postex.pk",
         "Fintech + logistics COD platform.",
         "Real-time logistics + fintech SaaS"),
        ("Trax Logistics", "https://trax.pk",
         "E-commerce logistics provider.",
         "Tracking APIs + dashboards"),
    ],

    "Food & Agriculture": [
        ("Tazah Technologies", "https://tazah.pk",
         "B2B fresh-produce supply chain.",
         "Real-time marketplace + dashboards"),
        ("Bazaar Technologies", "https://bazaartech.com",
         "B2B e-commerce for retailers.",
         "Full-stack SaaS at scale"),
        ("Krave Mart", "https://www.kravemart.com",
         "Quick-commerce grocery delivery.",
         "Real-time inventory + payments"),
        ("Dastgyr", "https://dastgyr.com",
         "B2B commerce platform for kiryana stores.",
         "Mobile + web SaaS, payments"),
        ("Cheetay", "https://cheetay.pk",
         "On-demand delivery (Lahore).",
         "Dispatch + real-time tracking"),
        ("GrocerApp", "https://grocerapp.pk",
         "Online grocery delivery.",
         "E-commerce + inventory"),
        ("Agrilift", "https://www.agrilift.pk",
         "AgriTech services and solutions.",
         "AgriTech SaaS, dashboards"),
    ],

    "Education & Training": [
        ("Sabaq Foundation", "https://www.sabaq.pk",
         "Free online education platform.",
         "Scalable learning platforms (500+ users)"),
        ("Nearpeer", "https://nearpeer.org",
         "Online academic learning platform.",
         "Real-time systems for live classes"),
        ("Out-Class", "https://www.out-class.org",
         "O/A Level online education startup.",
         "React + Node EdTech"),
        ("Maqsad", "https://maqsad.io",
         "Mobile-first EdTech for Pakistani students.",
         "AI integration + UX"),
        ("Knowledge Platform", "https://knowledgeplatform.com",
         "Digital learning solutions provider.",
         "SaaS platform engineering"),
        ("Edkasa", "https://edkasa.com",
         "Exam-prep EdTech for O/A Levels.",
         "Video + scheduling + MERN"),
        ("Orenda Education", "https://orenda.pk",
         "EdTech and school-improvement company.",
         "Learning analytics dashboards"),
        ("Taleemabad", "https://taleemabad.pk",
         "Low-cost EdTech for under-served schools.",
         "Mobile + web EdTech platform"),
    ],

    "Construction & Manufacturing": [
        ("Interloop Limited", "https://www.interloop-pk.com",
         "Global textile manufacturer; strong IT division.",
         "ERP / SaaS internal platforms"),
        ("Lucky Cement", "https://www.lucky-cement.com",
         "Leading cement manufacturer.",
         "Industrial dashboards + SaaS"),
        ("Engro Corporation", "https://www.engro.com",
         "Conglomerate (fertilizers, foods, energy).",
         "Enterprise web platforms"),
        ("Fauji Fertilizer Company", "https://www.ffc.com.pk",
         "Largest fertilizer manufacturer.",
         "Full-stack enterprise applications"),
        ("Nishat Mills", "https://nishatmillsltd.com",
         "Textile and apparel manufacturer.",
         "Internal tooling + dashboards"),
        ("Packages Group", "https://packagesgroup.com",
         "Packaging and consumer-products conglomerate.",
         "Enterprise web + SaaS"),
    ],

    "GovTech": [
        ("NADRA", "https://www.nadra.gov.pk",
         "National Database and Registration Authority.",
         "Large-scale gov digital services"),
        ("PITB", "https://pitb.gov.pk",
         "Punjab Information Technology Board.",
         "GovTech platforms + MERN"),
        ("KPITB", "https://kpitb.gov.pk",
         "Khyber Pakhtunkhwa IT Board.",
         "Digital public services engineering"),
        ("Ignite", "https://ignite.org.pk",
         "National Technology Fund.",
         "Full-stack product roles in gov programs"),
        ("Sindh IT Department", "https://sitd.gos.pk",
         "Sindh Information Technology Department.",
         "GovTech web applications"),
    ],

    "GreenTech": [
        ("EcoEnergy", "https://ecoenergy.com.pk",
         "Off-grid solar energy solutions.",
         "IoT + dashboards + React"),
        ("Reon Energy", "https://reonenergy.com",
         "Industrial solar and storage solutions.",
         "Energy monitoring SaaS"),
        ("Nizam Energy", "https://nizamenergy.com",
         "Renewable energy provider.",
         "Full-stack energy dashboards"),
        ("Zorays Solar", "https://zorays.com",
         "Solar EPC and monitoring.",
         "React + Node monitoring tools"),
        ("Shams Power", "https://shamspower.com",
         "Commercial solar power provider.",
         "Customer portals + dashboards"),
    ],

    "Cybersecurity": [
        ("Rewterz", "https://www.rewterz.com",
         "Cybersecurity services and threat intel.",
         "Security dashboards + full-stack"),
        ("Trillium Information Security", "https://trillium-infosec.com",
         "Cybersecurity consulting.",
         "SIEM / tooling front-ends"),
        ("Tranchulas", "https://www.tranchulas.com",
         "Offensive security and pen-testing.",
         "Security portal engineering"),
        ("Secureware", "https://secureware.com.pk",
         "Cybersecurity product and services.",
         "React + Node product engineering"),
        ("CyberForce", "https://cyberforce.pk",
         "Cybersecurity services company.",
         "Security SaaS dashboards"),
        ("Ebryx", "https://www.ebryx.com",
         "Cybersecurity products and services.",
         "Full-stack security products"),
    ],

    "AI & Data Science": [
        ("Afiniti Pakistan", "https://www.afiniti.com",
         "AI-powered behavioral pairing company.",
         "AI-integrated SaaS at large scale"),
        ("Systems Limited", "https://www.systemsltd.com",
         "Largest IT services exporter; strong AI practice.",
         "Full-stack AI product engineering"),
        ("Techlogix", "https://www.techlogix.com",
         "Technology consulting and AI solutions.",
         "Data-driven SaaS platforms"),
        ("Motive", "https://gomotive.com",
         "AI-driven fleet management (PK engineering hub).",
         "AI + real-time systems at scale"),
        ("Data Vault", "https://datavault.com.pk",
         "Data science and analytics consultancy.",
         "AI HR SaaS experience (facial recognition)"),
        ("Folio3", "https://www.folio3.com",
         "Software and AI product engineering.",
         "Full stack + AI integration"),
        ("10Pearls", "https://10pearls.com",
         "Digital product development + AI.",
         "Full-stack AI-enabled SaaS"),
        ("VentureDive", "https://venturedive.com",
         "Tech consulting / AI and data platforms.",
         "AI / data-heavy SaaS"),
        ("Tintash", "https://tintash.com",
         "Product engineering + AI services.",
         "AI-integrated full-stack"),
        ("Contour Software", "https://www.contour-software.com",
         "Global product engineering subsidiary.",
         "Full-stack + AI product roles"),
    ],
}


def iter_companies():
    """Yield dicts ready for the pipeline / CSV writer."""
    for vertical, entries in COMPANIES_BY_VERTICAL.items():
        for name, website, notes, custom in entries:
            yield {
                "vertical": vertical,
                "name": name,
                "website": website,
                "notes": notes,
                "custom": custom,
                "resume": resume_for_vertical(vertical),
                "email": CANDIDATE_EMAIL,
            }


if __name__ == "__main__":
    print(f"Total companies: {company_count()}")
    for vertical, entries in COMPANIES_BY_VERTICAL.items():
        print(f"  {vertical}: {len(entries)}")
